[package]
name = "bodhi-cli"
description = "bodhi CLI client based on bodhi-rs"
license = "MIT OR Apache-2.0"

version = "0.2.1"
edition = "2018"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["fedora", "bodhi", "CLI", "client"]
repository = "https://github.com/ironthree/bodhi-rs-cli"

[[bin]]
name = "bodhi-cli"
path = "src/main.rs"

[dependencies]
bodhi = "^0.4.0"
chrono = "^0.4.10"
dirs = "^2.0.2"
rpassword = "^4.0.3"
serde = { version = "^1.0.104", features = ["derive"] }
serde_json = "^1.0.44"
structopt = "^0.3.7"
term_size = "^0.2.1"
toml = "^0.5.5"

[profile.release]
codegen-units = 1
lto = true

